name: GitHub Actions Security Analysis with zizmor

on:
  push:
    branches:
      - master
      - main
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'
  pull_request:
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'

permissions:
  actions: read # Required by zizmor when reading workflow metadata through the API.
  contents: read # Required to read workflow files.

jobs:
  zizmor:
    name: Run zizmor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Create zizmor configuration
        run: |
          cat > .zizmor-shared.yml <<'YAML'
          rules:
            unpinned-uses:
              config:
                policies:
                  "yiisoft/*": any
          YAML

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5f14fd08f7cf1cb1609c1e344975f152c7ee938d # v0.5.6
        with:
          advanced-security: false
          annotations: true
          config: .zizmor-shared.yml
          inputs: .github
          min-severity: high
          persona: 'pedantic'
